spring.application.name=backend
spring.profiles.active=dev

jwt.secret=dGhpc0lzQVZlcnlTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb25JblNwcmluZ0Jvb3Q=
jwt.expiration=86400000

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.boot.autoconfigure.web=DEBUG
logging.level.org.hibernate.SQL=INFO

